### ISSUE TITLE
Adding another API style

### ISSUE THREAD

**Issue by simonbowly** [Gurobi/gurobipy-pandas#46]
Meta issue: discussion so far seems to have unearthed two possible usage patterns.

## Using dataframe columns as a namespace

This was the original design and is what the documentation and examples focuses on. In this mode, we expect all data relating to a given index to reside in one dataframe (e.g. sparse pairwise index for an assignment problem, with data for costs and limits). It then seems natural to create new variables as additional columns so that they live with relevant data which can be used when building constraints.

## Using python variables as a namespace

In this mode, various series of vars and data exist separately as different python variables. To create constraints, the user needs to align them as dataframes before using the accessors. In this situation, convenience functions which create constraints from aligned series are a better pattern.

Relevant discussions on other issues:

- https://github.com/Gurobi/gurobipy-pandas/issues/39
- https://github.com/Gurobi/gurobipy-pandas/issues/42

**Comment by simonbowly** [comment]
There are example of both styles in the docs. For reference:

- [Project-team allocation](https://gurobi-optimization-gurobipy-pandas.readthedocs-hosted.com/en/latest/examples/projects.html) shows creating all variables as series using the free functions
- [L1 norm regression](https://gurobi-optimization-gurobipy-pandas.readthedocs-hosted.com/en/latest/examples/regression.html) shows building all variables and constraints in the method chaining style using accessors

**Comment by Dr-Irv** [comment]
> There are example of both styles in the docs

OK, but earlier you wrote this:

> what's left is to add a page of documentation for each style to show pros/cons (typing support, data/variable separation, method chaining, maintaining series alignment)

Does that exist?  If not, do you have an issue to track it?

**Comment by simonbowly** [comment]
Yes, there is a section in the reference covering typing, and the usage page covers both styles. If you feel something is missing, feel free to raise an issue or PR.

**Comment by Dr-Irv** [comment]
> Yes, there is a section in the reference covering typing, and the usage page covers both styles. If you feel something is missing, feel free to raise an issue or PR.

Took a look, and I think what you have is good for now.  It will be interesting to see how people react to this new package.
