### ISSUE TITLE
Complete parameter documentation of add_vars

### ISSUE THREAD

**Issue by silkehorn** [Gurobi/gurobipy-pandas#67]
The [parameter documentation of the add_vars function](https://github.com/Gurobi/gurobipy-pandas/blob/3bbc86c8f22de8ba6559668b2db792adbff58dc6/src/gurobipy_pandas/api.py#L113) seems to be incomplete. It stops after `lb`.

**Comment by simonbowly** [comment]
Thanks! I'll update it

**Comment by Dr-Irv** [comment]
Just noticed this as well
